"use client";
// import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/Navbar";
import AuthProvider from "@/contex/AuthProvider";
import { usePathname } from "next/navigation";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const isPublicMsgPage = pathname.startsWith(`/u/`);
  return (
    <html lang="en">
      <body
        className={`antialiased flex flex-col h-[100dvh] ${!isPublicMsgPage ? "overflow-hidden" : ""}`}
      >
        <AuthProvider>
          {!isPublicMsgPage && <Navbar />}

          <main className="flex-1 relative overflow-hidden"> {children}</main>
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
